### ISSUE TITLE
[Bug]: Failed to generate DTS when running build twice

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#404]
### Version

```sh
Rslib 0.0.17
```

### Details

- Run Rslib twice: failed

![Image](https://github.com/user-attachments/assets/913c4c35-835f-4cb5-82a6-197c0f9758fe)

- Run tsc twice: succeed

![Image](https://github.com/user-attachments/assets/3bead099-dff1-4974-a401-9dda2abbc957)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/rslib_repro_types_1111

### Reproduce Steps

1. pnpm i
2. cd packages/core
3. pnpm run build && pnpm run build

**Comment by Timeless0911** [comment]
Since `composite: true` is set in `tsconfig.json`, the `incremental` will be default to `true`, thus creating a series of `.tsbuildinfo` files the same folder as your compilation output.

When we use `npx tsc`, it will generate `.tsbuildinfo` file. And for Rslib, we should use `dts.build: true` to align with this incremental build behaviour and this issue can be resolved.

For other Rsbuild plugins in Rsbuild repo, maybe `dts.build: true` should be enabled to keep the same behaviour with tsc. Since these plugins does not specify a special `declarationDir` that just keep the same value with the `outDir`, so this error does not appear.

Set `dts.build: true` will also generate types and buildinfo files for other projects in `references` which should be noted.

Modern.js Module just use bin file of `tsc`, so it do not need to do anything else. Rslib uses Typescript compiler API, and for composite project that have a special `declarationDir`, `dts.build: true` should be set.

**Comment by Timeless0911** [comment]
The `dts.build` options is designed to align with `--build` param for the tsc command. But for some special composite projects like `@rsbuild/core` that do not have `references`, it still need to enable `dts.build` to make it work like tsc normally.

What can we do for some default values of `dts.build`?

option 1. When `composite` is true, `dts.build` default to true. And in order to avoid buildinfo issue, we should automatically delete buildinfo file when `composite` is true too.

option 2. When `references` is true, `dts.build` default to true, and this will generate DTS and buildinfo files for other projects in references which may bring some issue in monorepo. Modern.js Module have used this behaviour before but encountered a lot of issues feedback, so [enableTscBuild](https://edenx.bytedance.net/module-tools/en/api/config/build-config.html#dtsenabletscbuild) options is added to dynamically enable this feature. This is a little different from `build: true` for packages like `@rsbuild/core` that do not have `references`. And I think this is the difference between simple compiler API and tsc bin.

**Comment by chenjiahan** [comment]
Get, I think Rslib can aim to align the default behaviour with `tsc`.
