### ISSUE TITLE
[Bug]: Failed to clean DTS output path

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rslib#405]
### Version

```sh
Rslib 0.0.17
```

### Details

The DTS output folder will not be cleaned if `dts.distPath` is not the `dist` folder.

- Example:

```ts
export default {
  lib: [
    {
      dts: {
        distPath: './dist-types',
      },
    },
  ],
}
```

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/main/packages/core

### Reproduce Steps

1. pnpm i
2. cd packages/core
3. pnpm run build

**Comment by Timeless0911** [comment]
This is a known issue and we have not supported it yet.

There are several points.

1. If the output folders of JS and DTS are the same, Rsbuild will help to handle this matter. The relevant Rsbuild configuration [output.cleanDistPath](https://rsbuild.dev/config/output/clean-dist-path) will affect the deletion of JS and DTS at the same time.
2. If the output folders of JS and DTS are different, the deletion of DTS files needs to be handled separately.

Two possible solutions for this feature:
1.Read the relevant configuration of Rsbuild to maintain the same logic as when the output folders are the same and control the deletion of JS and DTS at the same time, that is, when `output.cleanDistPath=false`, DTS will not be deleted too.
2. Support `dts.clean` option, which defaults to true, and controls the deletion of DTS output folder separately. 

Moreover, in order to avoid conflicts with the JS deletion behavior of Rsbuild, it is more appropriate to use glob to scan out DTS files for deletion. And the `.tsbuildinfo` file need to be deleted to align with behaviour with Modern.js Module.
